### ISSUE TITLE
Setting for Auto Update

### ISSUE THREAD

**Issue by mschroeder2** [somedowntime/libreofficegrouppolicy#4]
Is it possible to add appropriate settings to manage auto updates?  I need to be able to turn off updates via GPO.  Thanks!

**Comment by somedowntime** [comment]
Thanks for your interest in this project.

Unfortunately this project has sat on the backburner for myself. There is now a somewhat official group policy available here: https://libreoffice-from-collabora.com/windows-group-policy-admx/ (This is mentioned in the README.md) that should supersede this one.

That said, from memory you could not control the auto update by registry settings (group policy). It is a hell of a lot easier to just not install the auto update feature in the first place. The flags to the msi that disable the auto update are documented in the wiki here: https://github.com/somedowntime/libreofficegrouppolicy/wiki#Discouraged_Scenarios

If you already have LibreOffice installed on your domain computers, you can use group policy to uninstall your current setup and reinstall the version with Auto Update disabled.

**Comment by mschroeder2** [comment]
Thanks for your help Thomas.  I didn't know you could set this via msi
install.  I've changed that around and it seems to be working perfect now.

Matthew Schroeder
City of Neenah -- Information Systems
p: 920.886.6172
m: 920.209.2797
