### ISSUE TITLE
Support for later versions?

### ISSUE THREAD

**Issue by furicle** [somedowntime/libreofficegrouppolicy#6]
Is there a currently maintained version of these admx files anywhere?
The Collabra ones you link to seem to mention only up to 4. something, and this project is newer, but stops at 5.0

Oh wait, found https://github.com/CollaboraOnline/ADMX/blob/master/Collabora-Office.admx which mentions up to 5.3  

Am I correct in assuming those version numbers means it will not work with say 5.4 or 6.0?

**Comment by timar** [comment]
In LibreOffice world configuration is part of the stable API, in theory. That means, that a setting introduced in 5.0 will be supported forever. Those versions you found are the minimal supported versions. 5.4 and 6.0 are supported, too, of course. 

There may be rare exceptions, but this is the rule.

**Comment by somedowntime** [comment]
Thanks @timar for answering this question. @furicle, the Collabora maintained admx has far more options that my admx and is actively maintained. I stopped maintaining this group policy when Collabora released their admx file. I am going to close this issue as I see you have asked the question on the Collabora project.
