### ISSUE TITLE
Prefill user details

### ISSUE THREAD

**Issue by furicle** [somedowntime/libreofficegrouppolicy#7]
I'm trying to make this page work for us - https://github.com/somedowntime/libreofficegrouppolicy/wiki/Prefill-User-Details in a Windows AD environment.

I'm fairly confident I've completed the required editing, but NO user details are being filled.

Any suggestions on how to troubleshoot this?  How do I see if the server is getting a request?

**Comment by somedowntime** [comment]
Hi @furicle, I have just downloaded and installed LibreOffice (using LibreOffice_5.4.7_Win_x64.msi) and tested the steps that I have written in the above article, and apart from the fact that the folder is now **C:\Program Files\LibreOffice 5\share\registry**, the steps worked for me in my Active Directory environment.

My **oo-ad-ldap.xcd** file looks similar to the following. Please note the following:

1. I have only included the part of the file that is important.
2. You will need to replace the values with what matches your environment

```
 <dependency file="main"/>

  <oor:component-data oor:package="org.openoffice" oor:name="LDAP">

    <node oor:name="UserDirectory">

      <prop oor:name="SearchUser">

         <value>Domain\username</value>

      </prop>

      <prop oor:name="SearchPassword">

        <value>password</value>

      </prop>

      <prop oor:name="UserObjectClass">

       <value>user</value>

      </prop>

      <prop oor:name="UserUniqueAttribute">

        <value>cn</value>

      </prop>

      <node oor:name="ServerDefinition">

        <prop oor:name="Server">

          <value>domaincontroller01.ad.domain.com</value>

        </prop>

        <prop oor:name="Port">

          <value>389</value>

        </prop>

        <prop oor:name="BaseDN">

          <value>OU=UserOU,DC=ad,DC=domain,DC=com</value>

        </prop>

      </node>

    </node>

  </oor:component-data>
```

Make sure the user that you are using to bind to AD has read access to the relevant OU, additionally, you may have certain restrictions in place in your environment that restrict binding in plain text (port 636).

If you look in the **security** log on the domain controller that you used in **oo-ad-ldap.xcd**, you will see a logon event when you opened LibreOffice.

The documentation I wrote in the project wiki is a supplement to this project, if you really need help with this I would suggest asking your question at https://ask.libreoffice.org/en/questions/

Regards,
Thomas Higgins
